# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.images_collector.infrastructure.grpc.protos import images_pb2 as app_dot_images__collector_dot_infrastructure_dot_grpc_dot_protos_dot_images__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in app/images_collector/infrastructure/grpc/protos/images_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImageCollectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CollectImage = channel.unary_unary(
                '/images.ImageCollector/CollectImage',
                request_serializer=app_dot_images__collector_dot_infrastructure_dot_grpc_dot_protos_dot_images__pb2.ImageRequest.SerializeToString,
                response_deserializer=app_dot_images__collector_dot_infrastructure_dot_grpc_dot_protos_dot_images__pb2.ImageResponse.FromString,
                _registered_method=True)
        self.GetAllImages = channel.unary_unary(
                '/images.ImageCollector/GetAllImages',
                request_serializer=app_dot_images__collector_dot_infrastructure_dot_grpc_dot_protos_dot_images__pb2.EmptyRequest.SerializeToString,
                response_deserializer=app_dot_images__collector_dot_infrastructure_dot_grpc_dot_protos_dot_images__pb2.ImagesResponse.FromString,
                _registered_method=True)
        self.GetImageById = channel.unary_unary(
                '/images.ImageCollector/GetImageById',
                request_serializer=app_dot_images__collector_dot_infrastructure_dot_grpc_dot_protos_dot_images__pb2.ImageIdRequest.SerializeToString,
                response_deserializer=app_dot_images__collector_dot_infrastructure_dot_grpc_dot_protos_dot_images__pb2.ImageResponse.FromString,
                _registered_method=True)


class ImageCollectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CollectImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllImages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetImageById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageCollectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CollectImage': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectImage,
                    request_deserializer=app_dot_images__collector_dot_infrastructure_dot_grpc_dot_protos_dot_images__pb2.ImageRequest.FromString,
                    response_serializer=app_dot_images__collector_dot_infrastructure_dot_grpc_dot_protos_dot_images__pb2.ImageResponse.SerializeToString,
            ),
            'GetAllImages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllImages,
                    request_deserializer=app_dot_images__collector_dot_infrastructure_dot_grpc_dot_protos_dot_images__pb2.EmptyRequest.FromString,
                    response_serializer=app_dot_images__collector_dot_infrastructure_dot_grpc_dot_protos_dot_images__pb2.ImagesResponse.SerializeToString,
            ),
            'GetImageById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImageById,
                    request_deserializer=app_dot_images__collector_dot_infrastructure_dot_grpc_dot_protos_dot_images__pb2.ImageIdRequest.FromString,
                    response_serializer=app_dot_images__collector_dot_infrastructure_dot_grpc_dot_protos_dot_images__pb2.ImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'images.ImageCollector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('images.ImageCollector', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageCollector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CollectImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/images.ImageCollector/CollectImage',
            app_dot_images__collector_dot_infrastructure_dot_grpc_dot_protos_dot_images__pb2.ImageRequest.SerializeToString,
            app_dot_images__collector_dot_infrastructure_dot_grpc_dot_protos_dot_images__pb2.ImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/images.ImageCollector/GetAllImages',
            app_dot_images__collector_dot_infrastructure_dot_grpc_dot_protos_dot_images__pb2.EmptyRequest.SerializeToString,
            app_dot_images__collector_dot_infrastructure_dot_grpc_dot_protos_dot_images__pb2.ImagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetImageById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/images.ImageCollector/GetImageById',
            app_dot_images__collector_dot_infrastructure_dot_grpc_dot_protos_dot_images__pb2.ImageIdRequest.SerializeToString,
            app_dot_images__collector_dot_infrastructure_dot_grpc_dot_protos_dot_images__pb2.ImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
