# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/images_collector/infrastructure/grpc/protos/images.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'app/images_collector/infrastructure/grpc/protos/images.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<app/images_collector/infrastructure/grpc/protos/images.proto\x12\x06images\"\x0e\n\x0c\x45mptyRequest\"\x1c\n\x0eImageIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\".\n\x0cImageRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\"s\n\rImageResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x11\n\tfile_name\x18\x03 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x04 \x01(\t\x12\x0c\n\x04size\x18\x05 \x01(\x05\x12\x12\n\ncreated_at\x18\x06 \x01(\t\"7\n\x0eImagesResponse\x12%\n\x06images\x18\x01 \x03(\x0b\x32\x15.images.ImageResponse2\xca\x01\n\x0eImageCollector\x12;\n\x0c\x43ollectImage\x12\x14.images.ImageRequest\x1a\x15.images.ImageResponse\x12<\n\x0cGetAllImages\x12\x14.images.EmptyRequest\x1a\x16.images.ImagesResponse\x12=\n\x0cGetImageById\x12\x16.images.ImageIdRequest\x1a\x15.images.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.images_collector.infrastructure.grpc.protos.images_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTYREQUEST']._serialized_start=72
  _globals['_EMPTYREQUEST']._serialized_end=86
  _globals['_IMAGEIDREQUEST']._serialized_start=88
  _globals['_IMAGEIDREQUEST']._serialized_end=116
  _globals['_IMAGEREQUEST']._serialized_start=118
  _globals['_IMAGEREQUEST']._serialized_end=164
  _globals['_IMAGERESPONSE']._serialized_start=166
  _globals['_IMAGERESPONSE']._serialized_end=281
  _globals['_IMAGESRESPONSE']._serialized_start=283
  _globals['_IMAGESRESPONSE']._serialized_end=338
  _globals['_IMAGECOLLECTOR']._serialized_start=341
  _globals['_IMAGECOLLECTOR']._serialized_end=543
# @@protoc_insertion_point(module_scope)
